# Generated by Django 5.2.12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('consultas', '0002_remove_agudeza_from_consulta_and_estudio_choices'),
        ('historial_clinico', '0003_drop_modulos_hc_removidos'),
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionQuirurgica',
            fields=[
                ('id_evaluacion_quirurgica', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'estado_prequirurgico',
                    models.CharField(
                        choices=[
                            ('PENDIENTE', 'Pendiente'),
                            ('APTO', 'Apto'),
                            ('APTO_CON_OBSERVACIONES', 'Apto con observaciones'),
                            ('NO_APTO', 'No apto'),
                        ],
                        default='PENDIENTE',
                        max_length=32,
                    ),
                ),
                ('riesgo_quirurgico', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_estudios_complementarios', models.BooleanField(default=False)),
                ('estudios_solicitados', models.TextField(blank=True, null=True)),
                ('hallazgos', models.TextField(blank=True, null=True)),
                ('plan_quirurgico', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'evaluado_por',
                    models.ForeignKey(
                        blank=True,
                        db_column='evaluado_por',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='evaluaciones_quirurgicas_realizadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'id_consulta',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_consulta',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='evaluaciones_quirurgicas',
                        to='consultas.consulta',
                    ),
                ),
                (
                    'id_historia_clinica',
                    models.ForeignKey(
                        db_column='id_historia_clinica',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluaciones_quirurgicas',
                        to='historial_clinico.historiaclinica',
                    ),
                ),
                (
                    'id_paciente',
                    models.ForeignKey(
                        db_column='id_paciente',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluaciones_quirurgicas',
                        to='pacientes.paciente',
                    ),
                ),
            ],
            options={
                'db_table': 'evaluaciones_quirurgicas',
                'verbose_name': 'Evaluacion quirurgica',
                'verbose_name_plural': 'Evaluaciones quirurgicas',
                'ordering': ['-fecha_evaluacion', '-created_at'],
            },
        ),
    ]

