# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluacionQuirurgica",
            fields=[
                (
                    "id_evaluacion_quirurgica",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado_prequirurgico",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APTO", "Apto"),
                            ("APTO_CON_OBSERVACIONES", "Apto con observaciones"),
                            ("NO_APTO", "No apto"),
                        ],
                        default="PENDIENTE",
                        max_length=32,
                    ),
                ),
                (
                    "riesgo_quirurgico",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "requiere_estudios_complementarios",
                    models.BooleanField(default=False),
                ),
                ("estudios_solicitados", models.TextField(blank=True, null=True)),
                ("hallazgos", models.TextField(blank=True, null=True)),
                ("plan_quirurgico", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evaluacion quirurgica",
                "verbose_name_plural": "Evaluaciones quirurgicas",
                "db_table": "evaluaciones_quirurgicas",
                "ordering": ["-fecha_evaluacion", "-created_at"],
            },
        ),
    ]
