# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultas", "0002_initial"),
        ("evaluacion_quirurgica", "0001_initial"),
        ("historial_clinico", "0002_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacionquirurgica",
            name="evaluado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="evaluado_por",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones_quirurgicas_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluacionquirurgica",
            name="id_consulta",
            field=models.ForeignKey(
                blank=True,
                db_column="id_consulta",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones_quirurgicas",
                to="consultas.consulta",
            ),
        ),
        migrations.AddField(
            model_name="evaluacionquirurgica",
            name="id_historia_clinica",
            field=models.ForeignKey(
                db_column="id_historia_clinica",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones_quirurgicas",
                to="historial_clinico.historiaclinica",
            ),
        ),
        migrations.AddField(
            model_name="evaluacionquirurgica",
            name="id_paciente",
            field=models.ForeignKey(
                db_column="id_paciente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones_quirurgicas",
                to="pacientes.paciente",
            ),
        ),
    ]
