# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("especialistas", "0001_initial"),
        ("historial_clinico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receta",
            fields=[
                ("id_receta", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "fecha_receta",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("indicaciones_generales", models.TextField(blank=True, null=True)),
                (
                    "id_especialista",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_especialista",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recetas",
                        to="especialistas.especialista",
                    ),
                ),
                (
                    "id_historia_clinica",
                    models.ForeignKey(
                        db_column="id_historia_clinica",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas",
                        to="historial_clinico.historiaclinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta",
                "verbose_name_plural": "Recetas",
                "db_table": "recetas",
                "ordering": ["-fecha_receta"],
            },
        ),
        migrations.CreateModel(
            name="RecetaDetalle",
            fields=[
                (
                    "id_receta_detalle",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("medicamento", models.CharField(max_length=150)),
                ("dosis", models.CharField(blank=True, max_length=100, null=True)),
                ("frecuencia", models.CharField(blank=True, max_length=100, null=True)),
                ("duracion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "via_administracion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "id_receta",
                    models.ForeignKey(
                        db_column="id_receta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="recetas.receta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Receta",
                "verbose_name_plural": "Detalles de Receta",
                "db_table": "receta_detalles",
            },
        ),
    ]
