# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("cuerpo", models.TextField()),
                (
                    "tipo",
                    models.CharField(db_index=True, default="general", max_length=50),
                ),
                ("leida", models.BooleanField(db_index=True, default=False)),
                ("creada_en", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificaciones_notificacion",
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="DispositivoFcm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=512, unique=True)),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=16,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tenant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispositivos_fcm",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo FCM",
                "verbose_name_plural": "Dispositivos FCM",
                "db_table": "notificaciones_dispositivos_fcm",
            },
        ),
    ]
