# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    DispositivoFcm = apps.get_model('notificaciones', 'DispositivoFcm')
    Notificacion = apps.get_model('notificaciones', 'Notificacion')
    legacy = Tenant.objects.get(slug='legacy')
    DispositivoFcm.objects.filter(tenant__isnull=True).update(tenant=legacy)
    Notificacion.objects.filter(tenant__isnull=True).update(tenant=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('notificaciones', '0002_notificacion'),
        ('users', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivofcm',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='dispositivos_fcm', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='notificaciones', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
