# Generated by Django 5.2.14 on 2026-06-18 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia", "0001_initial"),
        ("pacientes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CriticalHumanHandoff",
            fields=[
                ("id_handoff", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "mensaje_original",
                    models.TextField(
                        help_text="Texto del mensaje enviado por el paciente que disparó la clasificación crítica."
                    ),
                ),
                (
                    "nivel_urgencia",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                            ("INSUFICIENTE", "Información insuficiente"),
                            ("INDETERMINADO", "No determinable"),
                        ],
                        default="CRITICO",
                        max_length=20,
                    ),
                ),
                (
                    "criterios_detectados",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Criterios de urgencia que matchearon en la clasificación.",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("NOTIFICADA", "Notificada"),
                            ("ASIGNADA", "Asignada"),
                            ("ACEPTADA", "Aceptada"),
                            ("EN_ATENCION", "En atención"),
                            ("RESUELTA", "Resuelta"),
                            ("FALLIDA", "Fallida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        help_text="Estado actual dentro del circuito de atención humana.",
                        max_length=20,
                    ),
                ),
                (
                    "notificado_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que se notificó al personal.",
                        null=True,
                    ),
                ),
                (
                    "aceptado_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que el caso fue aceptado.",
                        null=True,
                    ),
                ),
                (
                    "resuelto_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que el caso fue resuelto.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aceptado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Personal que aceptó formalmente atender el caso.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handoffs_aceptados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        help_text="Personal al que se le asignó este caso.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handoffs_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        db_column="id_clasificacion",
                        help_text="Clasificación CU24 que originó esta derivación.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoffs",
                        to="ia.chatboturgencyclassification",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoffs_criticos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Derivación a atención humana",
                "verbose_name_plural": "Derivaciones a atención humana",
                "db_table": "ia_critical_human_handoffs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["paciente", "-created_at"],
                        name="ia_ho_paciente_created_idx",
                    ),
                    models.Index(
                        fields=["estado", "-created_at"],
                        name="ia_ho_estado_created_idx",
                    ),
                ],
            },
        ),
    ]
