# Generated by Django 5.2.12 on 2026-04-12 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0002_initial"),
        ("pacientes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.TextField()),
                ("sintomas", models.TextField(blank=True)),
                ("notas_clinicas", models.TextField(blank=True)),
                (
                    "agudeza_visual_od",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Agudeza Visual Ojo Derecho",
                    ),
                ),
                (
                    "agudeza_visual_oi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Agudeza Visual Ojo Izquierdo",
                    ),
                ),
                (
                    "presion_intraocular_od",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Presión Intraocular Ojo Derecho",
                    ),
                ),
                (
                    "presion_intraocular_oi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Presión Intraocular Ojo Izquierdo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas",
                        to="citas.cita",
                    ),
                ),
                (
                    "especialista",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Estudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_estudio",
                    models.CharField(
                        choices=[
                            ("agudeza_visual", "Agudeza Visual"),
                            ("refraccion", "Refracción"),
                            ("tonometria", "Tonometría (Presión Intraocular)"),
                            ("fondo_ojo", "Fondo de Ojo"),
                            ("topografia", "Topografía Corneal"),
                            ("paquimetria", "Paquimetría"),
                            ("tomografia", "Tomografía de Coherencia Óptica (OCT)"),
                            ("campo_visual", "Campo Visual"),
                            ("otros", "Otros"),
                        ],
                        default="otros",
                        max_length=50,
                    ),
                ),
                (
                    "ojo_derecho",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Resultado Ojo Derecho",
                    ),
                ),
                (
                    "ojo_izquierdo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Resultado Ojo Izquierdo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones Clínicas"
                    ),
                ),
                (
                    "archivo_resultado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="estudios/resultados/",
                        verbose_name="Archivo/Resultados",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudios",
                        to="consultas.consulta",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudios",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudio Oftalmológico",
                "verbose_name_plural": "Estudios Oftalmológicos",
                "ordering": ["-fecha"],
            },
        ),
    ]
