# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultas", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("tenant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="especialista",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultas_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_column="id_tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultas",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="estudio",
            name="consulta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estudios",
                to="consultas.consulta",
            ),
        ),
        migrations.AddField(
            model_name="estudio",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estudios",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="estudio",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_column="id_tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estudios",
                to="tenant.tenant",
            ),
        ),
    ]
