# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    Consulta = apps.get_model('consultas', 'Consulta')
    Estudio = apps.get_model('consultas', 'Estudio')
    legacy = Tenant.objects.get(slug='legacy')

    for consulta in Consulta.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(consulta.paciente, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(consulta.cita, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(consulta.especialista, 'tenant', None)
        Consulta.objects.filter(pk=consulta.pk).update(tenant=related_tenant or legacy)

    for estudio in Estudio.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(estudio.paciente, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(estudio.consulta, 'tenant', None)
        Estudio.objects.filter(pk=estudio.pk).update(tenant=related_tenant or legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('consultas', '0002_remove_agudeza_from_consulta_and_estudio_choices'),
        ('pacientes', '0003_add_tenant'),
        ('citas', '0003_add_tenant'),
        ('users', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='consultas', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='estudios', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
