# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicion_visual", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicionvisual",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mediciones_visuales",
                to="pacientes.paciente",
            ),
        ),
    ]
