# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("especialistas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolucionClinica",
            fields=[
                (
                    "id_evolucion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_evolucion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("nota_evolucion", models.TextField()),
                (
                    "id_especialista",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_especialista",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evoluciones",
                        to="especialistas.especialista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evolución Clínica",
                "verbose_name_plural": "Evoluciones Clínicas",
                "db_table": "evoluciones_clinicas",
                "ordering": ["-fecha_evolucion"],
            },
        ),
    ]
