# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariorol",
            name="id_usuario",
            field=models.ForeignKey(
                db_column="id_usuario",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolpermiso",
            unique_together={("id_rol", "id_permiso")},
        ),
        migrations.AlterUniqueTogether(
            name="usuariorol",
            unique_together={("id_usuario", "id_rol")},
        ),
    ]
