# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("id_paciente", models.BigAutoField(primary_key=True, serialize=False)),
                ("numero_historia", models.CharField(max_length=30, unique=True)),
                ("tipo_documento", models.CharField(max_length=20)),
                ("numero_documento", models.CharField(max_length=30, unique=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=120, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "contacto_emergencia_nombre",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contacto_emergencia_telefono",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "estado_paciente",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("EN_SEGUIMIENTO", "En Seguimiento"),
                            ("POSTOPERATORIO", "Postoperatorio"),
                            ("INACTIVO", "Inactivo"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("observaciones_generales", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "pacientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
