# Generated by Django 5.2.12 on 2026-03-28 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticoClinico",
            fields=[
                (
                    "id_diagnostico",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("fecha_diagnostico", models.DateField(default=datetime.date.today)),
                ("descripcion", models.TextField()),
                ("cie10", models.CharField(blank=True, max_length=20, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Diagnóstico Clínico",
                "verbose_name_plural": "Diagnósticos Clínicos",
                "db_table": "diagnosticos_clinicos",
                "ordering": ["-fecha_diagnostico"],
            },
        ),
    ]
