# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnosticos", "0001_initial"),
        ("especialistas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticoclinico",
            name="id_especialista",
            field=models.ForeignKey(
                blank=True,
                db_column="id_especialista",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnosticos",
                to="especialistas.especialista",
            ),
        ),
    ]
