# Generated by Django 5.2.14 on 2026-06-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cobroclinico",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TARJETA", "Tarjeta"),
                    ("TRANSFERENCIA", "Transferencia bancaria"),
                    ("EN_LINEA", "Pago en línea"),
                    ("QR", "Pago QR"),
                ],
                max_length=20,
            ),
        ),
    ]
