# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id_plan", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PLUS", "Plus"), ("PRO", "Pro")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "precio_mensual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("moneda", models.CharField(default="BOB", max_length=10)),
                ("max_usuarios", models.PositiveIntegerField(default=3)),
                ("max_pacientes", models.PositiveIntegerField(default=100)),
                ("max_citas_mes", models.PositiveIntegerField(default=100)),
                ("max_almacenamiento_mb", models.PositiveIntegerField(default=500)),
                ("permite_crm", models.BooleanField(default=False)),
                ("permite_notificaciones", models.BooleanField(default=False)),
                ("permite_reportes_avanzados", models.BooleanField(default=False)),
                ("permite_soporte_prioritario", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan de suscripción",
                "verbose_name_plural": "Planes de suscripción",
                "db_table": "subscription_plans",
                "ordering": ["precio_mensual", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("id_tenant", models.BigAutoField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "razon_social",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                ("nit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "email_contacto",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "telefono_contacto",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "dominio_base",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
                "db_table": "tenant_tenants",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio",
                "verbose_name_plural": "Dominios",
                "db_table": "tenant_domains",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id_tenant_settings",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("timezone", models.CharField(default="America/La_Paz", max_length=64)),
                ("idioma", models.CharField(default="es", max_length=10)),
                (
                    "branding_nombre",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "branding_color_primario",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "branding_color_secundario",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("branding_logo_url", models.URLField(blank=True, default="")),
                ("flags", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        db_column="id_tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de organización",
                "verbose_name_plural": "Configuraciones de organizaciones",
                "db_table": "tenant_settings",
                "ordering": ["tenant__nombre"],
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id_suscripcion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("ACTIVA", "Activa"),
                            ("VENCIDA", "Vencida"),
                            ("CANCELADA", "Cancelada"),
                            ("SUSPENDIDA", "Suspendida"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("trial_fin", models.DateTimeField(blank=True, null=True)),
                ("renovar_automaticamente", models.BooleanField(default=False)),
                (
                    "proveedor_pago",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "referencia_pago",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        db_column="id_plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="tenant.subscriptionplan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        db_column="id_tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción de organización",
                "verbose_name_plural": "Suscripciones de organizaciones",
                "db_table": "tenant_subscriptions",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TenantUsage",
            fields=[
                ("id_usage", models.BigAutoField(primary_key=True, serialize=False)),
                ("usuarios_actuales", models.PositiveIntegerField(default=0)),
                ("pacientes_actuales", models.PositiveIntegerField(default=0)),
                ("citas_mes_actual", models.PositiveIntegerField(default=0)),
                ("almacenamiento_usado_mb", models.PositiveIntegerField(default=0)),
                ("periodo_anio", models.PositiveIntegerField(default=2026)),
                ("periodo_mes", models.PositiveIntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        db_column="id_tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso de organización",
                "verbose_name_plural": "Usos de organizaciones",
                "db_table": "tenant_usage",
            },
        ),
    ]
