# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id_tenant', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('dominio_base', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_tenants',
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id_tenant_settings', models.BigAutoField(primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='America/La_Paz', max_length=64)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('branding_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('branding_color_primario', models.CharField(blank=True, default='', max_length=20)),
                ('branding_color_secundario', models.CharField(blank=True, default='', max_length=20)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'tenant',
                    models.OneToOneField(
                        db_column='id_tenant',
                        on_delete=models.deletion.CASCADE,
                        related_name='settings',
                        to='tenant.tenant',
                    ),
                ),
            ],
            options={
                'db_table': 'tenant_settings',
                'verbose_name': 'Configuración de tenant',
                'verbose_name_plural': 'Configuraciones de tenant',
                'ordering': ['tenant__nombre'],
            },
        ),
    ]
