# Generated by Django 5.2.12

from django.db import migrations


def bootstrap_default_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    TenantSettings = apps.get_model('tenant', 'TenantSettings')

    tenant, _ = Tenant.objects.update_or_create(
        slug='legacy',
        defaults={
            'nombre': 'Legacy',
            'activo': True,
            'dominio_base': None,
        },
    )

    TenantSettings.objects.update_or_create(
        tenant=tenant,
        defaults={
            'timezone': 'America/La_Paz',
            'idioma': 'es',
            'branding_nombre': 'Legacy',
            'branding_color_primario': '',
            'branding_color_secundario': '',
            'flags': {'legacy_mode': True},
        },
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(bootstrap_default_tenant, noop_reverse),
    ]
