# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AntecedenteClinico",
            fields=[
                (
                    "id_antecedente",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_antecedente",
                    models.CharField(
                        choices=[
                            ("MEDICO", "Médico"),
                            ("OFTALMOLOGICO", "Oftalmológico"),
                            ("ALERGIA", "Alergia"),
                            ("FAMILIAR", "Familiar"),
                            ("QUIRURGICO", "Quirúrgico"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Antecedente Clínico",
                "verbose_name_plural": "Antecedentes Clínicos",
                "db_table": "antecedentes_clinicos",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
