# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("antecedentes", "0001_initial"),
        ("historial_clinico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antecedenteclinico",
            name="id_historia_clinica",
            field=models.ForeignKey(
                db_column="id_historia_clinica",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="antecedentes",
                to="historial_clinico.historiaclinica",
            ),
        ),
    ]
