# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("antecedentes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="antecedenteclinico",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="registrado_por",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="antecedentes_registrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
