# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bitacora",
            fields=[
                ("id_bitacora", models.BigAutoField(primary_key=True, serialize=False)),
                ("modulo", models.CharField(max_length=100)),
                (
                    "tabla_afectada",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("id_registro_afectado", models.BigIntegerField(blank=True, null=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("LOGIN_FALLIDO", "Login fallido"),
                            ("CREAR", "Crear registro"),
                            ("EDITAR", "Editar registro"),
                            ("ELIMINAR", "Eliminar registro"),
                            ("CAMBIAR_PASSWORD", "Cambio de contraseña"),
                            ("RECUPERAR_PASSWORD", "Recuperación de contraseña"),
                            ("REPROGRAMAR", "Reprogramar cita"),
                            ("CANCELAR", "Cancelar cita"),
                            ("CONFIRMAR", "Confirmar cita"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("ip_origen", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "fecha_evento",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Evento de Bitácora",
                "verbose_name_plural": "Bitácora",
                "db_table": "bitacora",
                "ordering": ["-fecha_evento"],
            },
        ),
    ]
