# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnosticos", "0002_initial"),
        ("especialistas", "0001_initial"),
        ("historial_clinico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TratamientoClinico",
            fields=[
                (
                    "id_tratamiento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.TextField()),
                ("indicaciones", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "id_diagnostico",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_diagnostico",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tratamientos",
                        to="diagnosticos.diagnosticoclinico",
                    ),
                ),
                (
                    "id_especialista",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_especialista",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tratamientos",
                        to="especialistas.especialista",
                    ),
                ),
                (
                    "id_historia_clinica",
                    models.ForeignKey(
                        db_column="id_historia_clinica",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tratamientos",
                        to="historial_clinico.historiaclinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento Clínico",
                "verbose_name_plural": "Tratamientos Clínicos",
                "db_table": "tratamientos_clinicos",
            },
        ),
    ]
