# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                ("id_cita", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha_hora_inicio", models.DateTimeField()),
                ("fecha_hora_fin", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("REPROGRAMADA", "Reprogramada"),
                            ("CANCELADA", "Cancelada"),
                            ("ATENDIDA", "Atendida"),
                            ("NO_ASISTIO", "No Asistió"),
                        ],
                        default="PROGRAMADA",
                        max_length=30,
                    ),
                ),
                ("motivo", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("confirmada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "db_table": "citas",
                "ordering": ["fecha_hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="DisponibilidadEspecialista",
            fields=[
                (
                    "id_disponibilidad",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "dia_semana",
                    models.IntegerField(help_text="1=Lunes, 2=Martes, ..., 7=Domingo"),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("intervalo_minutos", models.IntegerField(default=30)),
                ("fecha_desde", models.DateField(blank=True, null=True)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Disponibilidad de Especialista",
                "verbose_name_plural": "Disponibilidades de Especialistas",
                "db_table": "disponibilidades_especialista",
                "ordering": ["id_especialista", "dia_semana", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TipoCita",
            fields=[
                (
                    "id_tipo_cita",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("CONSULTA", "Consulta"),
                            ("ESTUDIO", "Estudio"),
                            ("CIRUGIA", "Cirugía"),
                            (
                                "SEGUIMIENTO_POSTOPERATORIO",
                                "Seguimiento Postoperatorio",
                            ),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Cita",
                "verbose_name_plural": "Tipos de Cita",
                "db_table": "tipos_cita",
            },
        ),
    ]
