# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("especialistas", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="creado_por",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cita",
            name="id_cita_reprogramada_desde",
            field=models.ForeignKey(
                blank=True,
                db_column="id_cita_reprogramada_desde",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reprogramaciones",
                to="citas.cita",
            ),
        ),
        migrations.AddField(
            model_name="cita",
            name="id_especialista",
            field=models.ForeignKey(
                db_column="id_especialista",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="citas",
                to="especialistas.especialista",
            ),
        ),
        migrations.AddField(
            model_name="cita",
            name="id_paciente",
            field=models.ForeignKey(
                db_column="id_paciente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citas",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="disponibilidadespecialista",
            name="id_especialista",
            field=models.ForeignKey(
                db_column="id_especialista",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disponibilidades",
                to="especialistas.especialista",
            ),
        ),
        migrations.AddField(
            model_name="cita",
            name="id_tipo_cita",
            field=models.ForeignKey(
                db_column="id_tipo_cita",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="citas",
                to="citas.tipocita",
            ),
        ),
    ]
