# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    Cita = apps.get_model('citas', 'Cita')
    DisponibilidadEspecialista = apps.get_model('citas', 'DisponibilidadEspecialista')
    legacy = Tenant.objects.get(slug='legacy')

    for disponibilidad in DisponibilidadEspecialista.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(disponibilidad.id_especialista, 'tenant', None)
        DisponibilidadEspecialista.objects.filter(pk=disponibilidad.pk).update(
            tenant=related_tenant or legacy,
        )

    for cita in Cita.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(cita.id_paciente, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(cita.id_especialista, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(cita.creado_por, 'tenant', None)
        Cita.objects.filter(pk=cita.pk).update(tenant=related_tenant or legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('citas', '0002_initial'),
        ('pacientes', '0003_add_tenant'),
        ('especialistas', '0003_add_tenant'),
        ('users', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadespecialista',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='disponibilidades_especialista', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='citas', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
