# Generated by Django 5.2.14 on 2026-05-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cirugia",
            fields=[
                ("id_cirugia", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "estado_cirugia",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("REPROGRAMADA", "Reprogramada"),
                            ("EN_CURSO", "En curso"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PROGRAMADA",
                        max_length=20,
                    ),
                ),
                ("fecha_programada", models.DateTimeField()),
                ("fecha_real_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_real_fin", models.DateTimeField(blank=True, null=True)),
                ("procedimiento", models.TextField()),
                ("resultado", models.TextField(blank=True, null=True)),
                ("complicaciones", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("motivo_reprogramacion", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cirugia",
                "verbose_name_plural": "Cirugias",
                "db_table": "cirugias",
                "ordering": ["-fecha_programada", "-created_at"],
            },
        ),
    ]
