# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('historial_clinico', '0003_drop_modulos_hc_removidos'),
        ('pacientes', '0002_initial'),
        ('preoperatorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id_cirugia', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'estado_cirugia',
                    models.CharField(
                        choices=[
                            ('PROGRAMADA', 'Programada'),
                            ('REPROGRAMADA', 'Reprogramada'),
                            ('EN_CURSO', 'En curso'),
                            ('FINALIZADA', 'Finalizada'),
                            ('CANCELADA', 'Cancelada'),
                        ],
                        default='PROGRAMADA',
                        max_length=20,
                    ),
                ),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_real_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_fin', models.DateTimeField(blank=True, null=True)),
                ('procedimiento', models.TextField()),
                ('resultado', models.TextField(blank=True, null=True)),
                ('complicaciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_reprogramacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'cirujano',
                    models.ForeignKey(
                        blank=True,
                        db_column='cirujano',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cirugias_realizadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'id_cita',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_cita',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cirugias',
                        to='citas.cita',
                    ),
                ),
                (
                    'id_historia_clinica',
                    models.ForeignKey(
                        db_column='id_historia_clinica',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cirugias',
                        to='historial_clinico.historiaclinica',
                    ),
                ),
                (
                    'id_paciente',
                    models.ForeignKey(
                        db_column='id_paciente',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cirugias',
                        to='pacientes.paciente',
                    ),
                ),
                (
                    'id_preoperatorio',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_preoperatorio',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cirugias',
                        to='preoperatorio.preoperatorio',
                    ),
                ),
            ],
            options={
                'db_table': 'cirugias',
                'verbose_name': 'Cirugia',
                'verbose_name_plural': 'Cirugias',
                'ordering': ['-fecha_programada', '-created_at'],
            },
        ),
    ]

