# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cirugias", "0001_initial"),
        ("citas", "0001_initial"),
        ("historial_clinico", "0002_initial"),
        ("pacientes", "0001_initial"),
        ("preoperatorio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cirugia",
            name="cirujano",
            field=models.ForeignKey(
                blank=True,
                db_column="cirujano",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cirugias_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cirugia",
            name="id_cita",
            field=models.ForeignKey(
                blank=True,
                db_column="id_cita",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cirugias",
                to="citas.cita",
            ),
        ),
        migrations.AddField(
            model_name="cirugia",
            name="id_historia_clinica",
            field=models.ForeignKey(
                db_column="id_historia_clinica",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cirugias",
                to="historial_clinico.historiaclinica",
            ),
        ),
        migrations.AddField(
            model_name="cirugia",
            name="id_paciente",
            field=models.ForeignKey(
                db_column="id_paciente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cirugias",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="cirugia",
            name="id_preoperatorio",
            field=models.ForeignKey(
                blank=True,
                db_column="id_preoperatorio",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cirugias",
                to="preoperatorio.preoperatorio",
            ),
        ),
    ]
