# Generated by Django 5.2.14 on 2026-05-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Especialista",
            fields=[
                (
                    "id_especialista",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_profesional",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("especialidad", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Especialista",
                "verbose_name_plural": "Especialistas",
                "db_table": "especialistas",
                "ordering": ["usuario__apellidos", "usuario__nombres"],
            },
        ),
    ]
