# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("especialistas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="especialista",
            name="usuario",
            field=models.OneToOneField(
                db_column="id_usuario",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="especialista",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
