# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    Especialista = apps.get_model('especialistas', 'Especialista')
    legacy = Tenant.objects.get(slug='legacy')
    Especialista.objects.filter(tenant__isnull=True).update(tenant=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('especialistas', '0002_initial'),
        ('users', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='especialistas', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
