# Generated by Django 5.2.14 on 2026-05-23 23:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0002_initial"),
        ("descuentos", "0001_initial"),
        ("pacientes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoServicioClinico",
            fields=[
                ("id_servicio", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("CONSULTA", "Consulta"),
                            ("ESTUDIO", "Estudio"),
                            ("CIRUGIA", "Cirugía"),
                            ("CONTROL", "Control / seguimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "precio_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_tipo_cita",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tipo_cita",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios_facturacion",
                        to="citas.tipocita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio clínico (tarifa)",
                "verbose_name_plural": "Catálogo de servicios clínicos",
                "db_table": "facturacion_catalogo_servicios",
                "ordering": ["tipo_servicio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="FacturaClinica",
            fields=[
                ("id_factura", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "numero_factura",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EMITIDA", "Emitida"),
                            ("PAGADA_PARCIAL", "Pagada parcial"),
                            ("PAGADA", "Pagada"),
                            ("ANULADA", "Anulada"),
                        ],
                        db_index=True,
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("fecha_emision", models.DateField(default=django.utils.timezone.now)),
                (
                    "fecha_referencia_calculo",
                    models.DateField(
                        help_text="Fecha usada para vigencia de seguro/descuento."
                    ),
                ),
                (
                    "monto_base",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "monto_cobertura_seguro",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "copago_seguro",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "monto_descuento",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto a cargo del paciente tras seguro y descuento.",
                        max_digits=12,
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("detalle_calculo", models.JSONField(blank=True, default=dict)),
                ("observaciones", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="creado_por",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_clinicas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_cita",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cita",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas",
                        to="citas.cita",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_clinicas",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "id_promocion_aplicada",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_promocion_aplicada",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas",
                        to="descuentos.promociondescuento",
                    ),
                ),
                (
                    "id_servicio",
                    models.ForeignKey(
                        db_column="id_servicio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="facturacion.catalogoservicioclinico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura clínica",
                "verbose_name_plural": "Facturas clínicas",
                "db_table": "facturacion_facturas",
                "ordering": ["-fecha_emision", "-id_factura"],
            },
        ),
        migrations.CreateModel(
            name="CobroClinico",
            fields=[
                ("id_cobro", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("EN_LINEA", "Pago en línea"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("RECHAZADO", "Rechazado"),
                            ("ANULADO", "Anulado"),
                        ],
                        db_index=True,
                        default="CONFIRMADO",
                        max_length=20,
                    ),
                ),
                (
                    "referencia_pasarela",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID de transacción externa (pasarela) cuando metodo_pago=EN_LINEA.",
                        max_length=120,
                    ),
                ),
                (
                    "fecha_cobro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="registrado_por",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cobros_clinicos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_factura",
                    models.ForeignKey(
                        db_column="id_factura",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobros",
                        to="facturacion.facturaclinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobro clínico",
                "verbose_name_plural": "Cobros clínicos",
                "db_table": "facturacion_cobros",
                "ordering": ["-fecha_cobro"],
            },
        ),
    ]
