# Generated by Django 5.2.12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentacionPaciente',
            fields=[
                ('id_segmentacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('criterios', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_segmentaciones',
                'verbose_name': 'Segmentacion de pacientes',
                'verbose_name_plural': 'Segmentaciones de pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CampanaCRM',
            fields=[
                ('id_campana', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('BORRADOR', 'Borrador'),
                            ('ACTIVA', 'Activa'),
                            ('PAUSADA', 'Pausada'),
                            ('FINALIZADA', 'Finalizada'),
                        ],
                        default='BORRADOR',
                        max_length=20,
                    ),
                ),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'creado_por',
                    models.ForeignKey(
                        blank=True,
                        db_column='creado_por',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='campanas_crm_creadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'id_segmentacion',
                    models.ForeignKey(
                        db_column='id_segmentacion',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='campanas',
                        to='crm.segmentacionpaciente',
                    ),
                ),
            ],
            options={
                'db_table': 'crm_campanas',
                'verbose_name': 'Campana CRM',
                'verbose_name_plural': 'Campanas CRM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContacto',
            fields=[
                ('id_historial_contacto', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'canal',
                    models.CharField(
                        choices=[
                            ('LLAMADA', 'Llamada'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('EMAIL', 'Email'),
                            ('SMS', 'SMS'),
                            ('OTRO', 'Otro'),
                        ],
                        max_length=20,
                    ),
                ),
                ('fecha_contacto', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'contactado_por',
                    models.ForeignKey(
                        blank=True,
                        db_column='contactado_por',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='crm_contactos_registrados',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'id_campana',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_campana',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='historial_contactos',
                        to='crm.campanacrm',
                    ),
                ),
                (
                    'id_paciente',
                    models.ForeignKey(
                        db_column='id_paciente',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='crm_historial_contactos',
                        to='pacientes.paciente',
                    ),
                ),
            ],
            options={
                'db_table': 'crm_historial_contactos',
                'verbose_name': 'Historial de contacto',
                'verbose_name_plural': 'Historiales de contacto',
                'ordering': ['-fecha_contacto', '-created_at'],
            },
        ),
    ]
