# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampanaCRM",
            fields=[
                ("id_campana", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ACTIVA", "Activa"),
                            ("PAUSADA", "Pausada"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campana CRM",
                "verbose_name_plural": "Campanas CRM",
                "db_table": "crm_campanas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialContacto",
            fields=[
                (
                    "id_historial_contacto",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("LLAMADA", "Llamada"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fecha_contacto",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resultado", models.CharField(blank=True, max_length=150, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Historial de contacto",
                "verbose_name_plural": "Historiales de contacto",
                "db_table": "crm_historial_contactos",
                "ordering": ["-fecha_contacto", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SegmentacionPaciente",
            fields=[
                (
                    "id_segmentacion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("criterios", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Segmentacion de pacientes",
                "verbose_name_plural": "Segmentaciones de pacientes",
                "db_table": "crm_segmentaciones",
                "ordering": ["nombre"],
            },
        ),
    ]
