# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campanacrm",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="creado_por",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campanas_crm_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialcontacto",
            name="contactado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="contactado_por",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_contactos_registrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialcontacto",
            name="id_campana",
            field=models.ForeignKey(
                blank=True,
                db_column="id_campana",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historial_contactos",
                to="crm.campanacrm",
            ),
        ),
        migrations.AddField(
            model_name="historialcontacto",
            name="id_paciente",
            field=models.ForeignKey(
                db_column="id_paciente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_historial_contactos",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddConstraint(
            model_name="segmentacionpaciente",
            constraint=models.UniqueConstraint(
                fields=("nombre",), name="crm_segmentacion_nombre_uniq"
            ),
        ),
        migrations.AddField(
            model_name="campanacrm",
            name="id_segmentacion",
            field=models.ForeignKey(
                db_column="id_segmentacion",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campanas",
                to="crm.segmentacionpaciente",
            ),
        ),
    ]
