# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    SegmentacionPaciente = apps.get_model('crm', 'SegmentacionPaciente')
    CampanaCRM = apps.get_model('crm', 'CampanaCRM')
    HistorialContacto = apps.get_model('crm', 'HistorialContacto')
    legacy = Tenant.objects.get(slug='legacy')

    for segmentacion in SegmentacionPaciente.objects.filter(tenant__isnull=True).iterator():
        SegmentacionPaciente.objects.filter(pk=segmentacion.pk).update(tenant=legacy)

    for campana in CampanaCRM.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(campana.id_segmentacion, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(campana.creado_por, 'tenant', None)
        CampanaCRM.objects.filter(pk=campana.pk).update(tenant=related_tenant or legacy)

    for contacto in HistorialContacto.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(contacto.id_paciente, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(contacto.id_campana, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(contacto.contactado_por, 'tenant', None)
        HistorialContacto.objects.filter(pk=contacto.pk).update(tenant=related_tenant or legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('crm', '0001_initial'),
        ('pacientes', '0003_add_tenant'),
        ('users', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentacionpaciente',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='crm_segmentaciones', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='campanacrm',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='crm_campanas', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='historialcontacto',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='crm_historial_contactos', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='segmentacionpaciente',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='segmentacionpaciente',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='crm_segmentacion_tenant_nombre_uniq'),
        ),
    ]
