# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("permisos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo", models.SlugField(max_length=60, unique=True)),
                ("nombre", models.CharField(max_length=80)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el rol fue creado por el sistema base.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre",), name="unique_nombre_rol_por_schema"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RolPermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "id_permiso",
                    models.ForeignKey(
                        db_column="id_permiso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rol_permisos",
                        to="permisos.permiso",
                    ),
                ),
                (
                    "id_rol",
                    models.ForeignKey(
                        db_column="id_rol",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rol_permisos",
                        to="roles.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol-Permiso",
                "verbose_name_plural": "Asignaciones Rol-Permiso",
                "db_table": "rol_permiso",
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "id_rol",
                    models.ForeignKey(
                        db_column="id_rol",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_roles",
                        to="roles.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Rol",
                "verbose_name_plural": "Asignaciones Usuario-Rol",
                "db_table": "usuario_rol",
            },
        ),
    ]
