# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariorol",
            name="id_usuario",
            field=models.ForeignKey(
                db_column="id_usuario",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="rolpermiso",
            constraint=models.UniqueConstraint(
                fields=("id_rol", "id_permiso"), name="unique_rol_permiso_por_schema"
            ),
        ),
        migrations.AddConstraint(
            model_name="usuariorol",
            constraint=models.UniqueConstraint(
                fields=("id_usuario", "id_rol"), name="unique_usuario_rol_por_schema"
            ),
        ),
    ]
