# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    Usuario = apps.get_model('users', 'Usuario')
    legacy = Tenant.objects.get(slug='legacy')
    Usuario.objects.filter(tenant__isnull=True).update(tenant=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='usuarios', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
