# Generated by Django 5.2.14 on 2026-05-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEjecucionRecordatorio",
            fields=[
                ("id_log", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nivel",
                    models.CharField(
                        choices=[("INFO", "Info"), ("ERROR", "Error")],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("mensaje", models.CharField(max_length=255)),
                ("detalle", models.TextField(blank=True, null=True)),
                (
                    "ejecutado_en",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "verbose_name": "Log de ejecución de recordatorio",
                "verbose_name_plural": "Logs de ejecución de recordatorio",
                "db_table": "notificaciones_logs_recordatorio",
                "ordering": ["-ejecutado_en"],
            },
        ),
        migrations.CreateModel(
            name="ReglaRecordatorio",
            fields=[
                ("id_regla", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=120)),
                (
                    "tipo_regla",
                    models.CharField(
                        choices=[("CONTROL_POSTOPERATORIO", "Control postoperatorio")],
                        default="CONTROL_POSTOPERATORIO",
                        max_length=40,
                    ),
                ),
                ("horas_antes", models.PositiveIntegerField(default=24)),
                ("titulo_template", models.CharField(max_length=200)),
                ("cuerpo_template", models.TextField()),
                ("activa", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Regla de recordatorio",
                "verbose_name_plural": "Reglas de recordatorio",
                "db_table": "notificaciones_reglas_recordatorio",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TareaRecordatorioProgramada",
            fields=[
                ("id_tarea", models.BigAutoField(primary_key=True, serialize=False)),
                ("programada_para", models.DateTimeField(db_index=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESADA", "Procesada"),
                            ("ERROR", "Error"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                ("procesada_en", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tarea de recordatorio",
                "verbose_name_plural": "Tareas de recordatorio",
                "db_table": "notificaciones_tareas_recordatorio",
                "ordering": ["programada_para"],
            },
        ),
    ]
