# Generated by Django 5.2.14 on 2026-05-09 20:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBackupConfig',
            fields=[
                ('id_config', models.BigAutoField(primary_key=True, serialize=False)),
                ('backup_automatico', models.BooleanField(default=True, help_text='Si está activado, se ejecutan backups automáticos')),
                ('hora_backup', models.TimeField(default=datetime.time(3, 0), help_text='Hora del backup automático (America/La_Paz)')),
                ('frecuencia', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal')], default='daily', help_text='Frecuencia de backups automáticos', max_length=10)),
                ('retencion_dias', models.IntegerField(default=7, help_text='Días de retención de backups')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Backup Automático',
                'verbose_name_plural': 'Configuraciones de Backup Automático',
                'db_table': 'tenant_backup_configs',
            },
        ),
        migrations.CreateModel(
            name='TenantBackup',
            fields=[
                ('id_backup', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.CharField(help_text='Ruta del archivo en storage (ej: backups/123/20260509_030000.sql.gz)', max_length=500)),
                ('tamaño_mb', models.DecimalField(decimal_places=2, help_text='Tamaño del backup en MB', max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('RESTAURADO', 'Restaurado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(help_text='Fecha de expiración según retención del plan')),
                ('restaurado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_restore', models.TextField(blank=True, default='', help_text='Motivo de la restauración (obligatorio para auditoría)')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to=settings.AUTH_USER_MODEL)),
                ('restaurado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_restaurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup de organización',
                'verbose_name_plural': 'Backups de organizaciones',
                'db_table': 'tenant_backups',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado'], name='tenant_back_estado_cf8160_idx'), models.Index(fields=['creado_en'], name='tenant_back_creado__025bc1_idx'), models.Index(fields=['expira_en'], name='tenant_back_expira__952da2_idx')],
            },
        ),
    ]
