# Generated by Django 5.2.14 on 2026-05-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                ("id_permiso", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Código único del permiso. Ej: pacientes.crear",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "modulo",
                    models.CharField(
                        help_text="Módulo funcional. Ej: pacientes, citas, usuarios",
                        max_length=80,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el permiso pertenece al catálogo base del sistema.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "permisos",
                "ordering": ["modulo", "codigo"],
            },
        ),
    ]
