# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("evaluacion_quirurgica", "0001_initial"),
        ("historial_clinico", "0002_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preoperatorio",
            fields=[
                (
                    "id_preoperatorio",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "estado_preoperatorio",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("APROBADO", "Aprobado"),
                            ("OBSERVADO", "Observado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("checklist_completado", models.BooleanField(default=False)),
                ("checklist_detalle", models.TextField(blank=True, null=True)),
                ("examenes_requeridos", models.TextField(blank=True, null=True)),
                ("examenes_completados", models.TextField(blank=True, null=True)),
                ("apto_anestesia", models.BooleanField(default=False)),
                (
                    "fecha_programada_cirugia",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_cita",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cita",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preoperatorios",
                        to="citas.cita",
                    ),
                ),
                (
                    "id_evaluacion_quirurgica",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_evaluacion_quirurgica",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preoperatorios",
                        to="evaluacion_quirurgica.evaluacionquirurgica",
                    ),
                ),
                (
                    "id_historia_clinica",
                    models.ForeignKey(
                        db_column="id_historia_clinica",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preoperatorios",
                        to="historial_clinico.historiaclinica",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preoperatorios",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preoperatorio",
                "verbose_name_plural": "Preoperatorios",
                "db_table": "preoperatorios",
                "ordering": ["-created_at"],
            },
        ),
    ]
