# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preoperatorio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preoperatorio",
            name="validado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="validado_por",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preoperatorios_validados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
