# Generated by Django 5.2.12 on 2026-03-28 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoriaClinica",
            fields=[
                (
                    "id_historia_clinica",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("fecha_apertura", models.DateField(default=datetime.date.today)),
                ("motivo_apertura", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("CERRADA", "Cerrada"),
                            ("ARCHIVADA", "Archivada"),
                        ],
                        default="ACTIVA",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
                "db_table": "historias_clinicas",
            },
        ),
    ]
