# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("historial_clinico", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historiaclinica",
            name="id_paciente",
            field=models.OneToOneField(
                db_column="id_paciente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historia_clinica",
                to="pacientes.paciente",
            ),
        ),
    ]
