# Generated by Django 5.2.14 on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0002_initial'),
        ('pacientes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoClinicoAutorizado',
            fields=[
                (
                    'id_documento_clinico',
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    'tipo_documento',
                    models.CharField(
                        choices=[('RECETA', 'Receta'), ('INDICACION', 'Indicación')],
                        default='RECETA',
                        max_length=20,
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('BORRADOR', 'Borrador'),
                            ('AUTORIZADO', 'Autorizado'),
                            ('ANULADO', 'Anulado'),
                        ],
                        default='BORRADOR',
                        max_length=20,
                    ),
                ),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                (
                    'nombre_archivo_descarga',
                    models.CharField(blank=True, default='', max_length=180),
                ),
                (
                    'fecha_emision',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'autorizado_en',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'autorizado_por',
                    models.ForeignKey(
                        blank=True,
                        db_column='autorizado_por',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='documentos_clinicos_autorizados',
                        to='users.usuario',
                    ),
                ),
                (
                    'id_historia_clinica',
                    models.ForeignKey(
                        db_column='id_historia_clinica',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documentos_clinicos',
                        to='historial_clinico.historiaclinica',
                    ),
                ),
                (
                    'id_paciente',
                    models.ForeignKey(
                        db_column='id_paciente',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documentos_clinicos',
                        to='pacientes.paciente',
                    ),
                ),
            ],
            options={
                'db_table': 'documentos_clinicos_autorizados',
                'verbose_name': 'Documento Clínico Autorizado',
                'verbose_name_plural': 'Documentos Clínicos Autorizados',
                'ordering': ['-autorizado_en', '-fecha_emision', '-created_at'],
                'indexes': [
                    models.Index(fields=['id_historia_clinica', 'estado'], name='doc_hist_estado_idx'),
                    models.Index(fields=['id_paciente', 'estado'], name='doc_pac_estado_idx'),
                ],
            },
        ),
    ]
