# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    HistoriaClinica = apps.get_model('historial_clinico', 'HistoriaClinica')
    legacy = Tenant.objects.get(slug='legacy')
    HistoriaClinica.objects.filter(tenant__isnull=True).update(tenant=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('pacientes', '0003_add_tenant'),
        ('historial_clinico', '0003_drop_modulos_hc_removidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='historias_clinicas', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
