# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('pacientes', '0002_initial'),
        ('postoperatorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaRecordatorio',
            fields=[
                ('id_regla', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                (
                    'tipo_regla',
                    models.CharField(
                        choices=[('CONTROL_POSTOPERATORIO', 'Control postoperatorio')],
                        default='CONTROL_POSTOPERATORIO',
                        max_length=40,
                    ),
                ),
                ('horas_antes', models.PositiveIntegerField(default=24)),
                ('titulo_template', models.CharField(max_length=200)),
                ('cuerpo_template', models.TextField()),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'creado_por',
                    models.ForeignKey(
                        blank=True,
                        db_column='creado_por',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reglas_recordatorio_creadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'notificaciones_reglas_recordatorio',
                'verbose_name': 'Regla de recordatorio',
                'verbose_name_plural': 'Reglas de recordatorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TareaRecordatorioProgramada',
            fields=[
                ('id_tarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('programada_para', models.DateTimeField(db_index=True)),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('PENDIENTE', 'Pendiente'),
                            ('PROCESADA', 'Procesada'),
                            ('ERROR', 'Error'),
                            ('CANCELADA', 'Cancelada'),
                        ],
                        db_index=True,
                        default='PENDIENTE',
                        max_length=20,
                    ),
                ),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('procesada_en', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id_paciente',
                    models.ForeignKey(
                        db_column='id_paciente',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recordatorios_programados',
                        to='pacientes.paciente',
                    ),
                ),
                (
                    'id_postoperatorio',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_postoperatorio',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recordatorios_programados',
                        to='postoperatorio.postoperatorio',
                    ),
                ),
                (
                    'id_regla',
                    models.ForeignKey(
                        db_column='id_regla',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='tareas_programadas',
                        to='automatizaciones.reglarecordatorio',
                    ),
                ),
            ],
            options={
                'db_table': 'notificaciones_tareas_recordatorio',
                'verbose_name': 'Tarea de recordatorio',
                'verbose_name_plural': 'Tareas de recordatorio',
                'ordering': ['programada_para'],
            },
        ),
        migrations.CreateModel(
            name='LogEjecucionRecordatorio',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'nivel',
                    models.CharField(
                        choices=[('INFO', 'Info'), ('ERROR', 'Error')],
                        default='INFO',
                        max_length=10,
                    ),
                ),
                ('mensaje', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'id_tarea',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_tarea',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='logs',
                        to='automatizaciones.tarearecordatorioprogramada',
                    ),
                ),
            ],
            options={
                'db_table': 'notificaciones_logs_recordatorio',
                'verbose_name': 'Log de ejecución de recordatorio',
                'verbose_name_plural': 'Logs de ejecución de recordatorio',
                'ordering': ['-ejecutado_en'],
            },
        ),
    ]
