# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automatizaciones", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("postoperatorio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reglarecordatorio",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="creado_por",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reglas_recordatorio_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tarearecordatorioprogramada",
            name="id_paciente",
            field=models.ForeignKey(
                db_column="id_paciente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios_programados",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="tarearecordatorioprogramada",
            name="id_postoperatorio",
            field=models.ForeignKey(
                blank=True,
                db_column="id_postoperatorio",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios_programados",
                to="postoperatorio.postoperatorio",
            ),
        ),
        migrations.AddField(
            model_name="tarearecordatorioprogramada",
            name="id_regla",
            field=models.ForeignKey(
                db_column="id_regla",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tareas_programadas",
                to="automatizaciones.reglarecordatorio",
            ),
        ),
        migrations.AddField(
            model_name="logejecucionrecordatorio",
            name="id_tarea",
            field=models.ForeignKey(
                blank=True,
                db_column="id_tarea",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="automatizaciones.tarearecordatorioprogramada",
            ),
        ),
        migrations.AddConstraint(
            model_name="reglarecordatorio",
            constraint=models.UniqueConstraint(
                fields=("nombre",), name="recordatorio_nombre_uniq"
            ),
        ),
    ]
