# Generated by Django 5.2.12

from django.db import migrations, models


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')
    ReglaRecordatorio = apps.get_model('automatizaciones', 'ReglaRecordatorio')
    TareaRecordatorioProgramada = apps.get_model('automatizaciones', 'TareaRecordatorioProgramada')
    LogEjecucionRecordatorio = apps.get_model('automatizaciones', 'LogEjecucionRecordatorio')
    legacy = Tenant.objects.get(slug='legacy')

    for regla in ReglaRecordatorio.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(regla.creado_por, 'tenant', None)
        ReglaRecordatorio.objects.filter(pk=regla.pk).update(tenant=related_tenant or legacy)

    for tarea in TareaRecordatorioProgramada.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(tarea.id_paciente, 'tenant', None)
        if related_tenant is None:
            related_tenant = getattr(tarea.id_regla, 'tenant', None)
        if related_tenant is None and tarea.id_postoperatorio_id:
            related_tenant = getattr(tarea.id_postoperatorio.id_paciente, 'tenant', None)
        TareaRecordatorioProgramada.objects.filter(pk=tarea.pk).update(tenant=related_tenant or legacy)

    for log in LogEjecucionRecordatorio.objects.filter(tenant__isnull=True).iterator():
        related_tenant = getattr(log.id_tarea, 'tenant', None)
        LogEjecucionRecordatorio.objects.filter(pk=log.pk).update(tenant=related_tenant or legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_bootstrap_default_tenant'),
        ('automatizaciones', '0001_initial'),
        ('pacientes', '0003_add_tenant'),
        ('postoperatorio', '0001_initial'),
        ('users', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglarecordatorio',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='reglas_recordatorio', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='tarearecordatorioprogramada',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='tareas_recordatorio', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='logejecucionrecordatorio',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=models.deletion.SET_NULL, related_name='logs_recordatorio', to='tenant.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reglarecordatorio',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='reglarecordatorio',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='recordatorio_tenant_nombre_uniq'),
        ),
    ]
