# Generated by Django 5.2.14 on 2026-05-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cirugias", "0001_initial"),
        ("historial_clinico", "0002_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postoperatorio",
            fields=[
                (
                    "id_postoperatorio",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "estado_postoperatorio",
                    models.CharField(
                        choices=[
                            ("ESTABLE", "Estable"),
                            ("EN_OBSERVACION", "En observacion"),
                            ("COMPLICADO", "Complicado"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="EN_OBSERVACION",
                        max_length=20,
                    ),
                ),
                ("fecha_control", models.DateTimeField()),
                ("proximo_control", models.DateTimeField(blank=True, null=True)),
                ("alertas", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_cirugia",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cirugia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postoperatorios",
                        to="cirugias.cirugia",
                    ),
                ),
                (
                    "id_historia_clinica",
                    models.ForeignKey(
                        db_column="id_historia_clinica",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postoperatorios",
                        to="historial_clinico.historiaclinica",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postoperatorios",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postoperatorio",
                "verbose_name_plural": "Postoperatorios",
                "db_table": "postoperatorios",
                "ordering": ["-fecha_control", "-created_at"],
            },
        ),
    ]
