# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cirugias', '0001_initial'),
        ('historial_clinico', '0003_drop_modulos_hc_removidos'),
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postoperatorio',
            fields=[
                ('id_postoperatorio', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'estado_postoperatorio',
                    models.CharField(
                        choices=[
                            ('ESTABLE', 'Estable'),
                            ('EN_OBSERVACION', 'En observacion'),
                            ('COMPLICADO', 'Complicado'),
                            ('CERRADO', 'Cerrado'),
                        ],
                        default='EN_OBSERVACION',
                        max_length=20,
                    ),
                ),
                ('fecha_control', models.DateTimeField()),
                ('proximo_control', models.DateTimeField(blank=True, null=True)),
                ('alertas', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id_cirugia',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_cirugia',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='postoperatorios',
                        to='cirugias.cirugia',
                    ),
                ),
                (
                    'id_historia_clinica',
                    models.ForeignKey(
                        db_column='id_historia_clinica',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='postoperatorios',
                        to='historial_clinico.historiaclinica',
                    ),
                ),
                (
                    'id_paciente',
                    models.ForeignKey(
                        db_column='id_paciente',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='postoperatorios',
                        to='pacientes.paciente',
                    ),
                ),
                (
                    'profesional_atiende',
                    models.ForeignKey(
                        blank=True,
                        db_column='profesional_atiende',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='postoperatorios_atendidos',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'postoperatorios',
                'verbose_name': 'Postoperatorio',
                'verbose_name_plural': 'Postoperatorios',
                'ordering': ['-fecha_control', '-created_at'],
            },
        ),
    ]
