# Generated by Django 5.2.14 on 2026-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postoperatorio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="postoperatorio",
            name="profesional_atiende",
            field=models.ForeignKey(
                blank=True,
                db_column="profesional_atiende",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="postoperatorios_atendidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
